// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Jn_QsFEqCeu4tnbvwNN4LNE7bqTyFtQ',
    appId: '1:72236930132:web:c8209768a3d2b79f5049c1',
    messagingSenderId: '72236930132',
    projectId: 'formula-e-book',
    authDomain: 'formula-e-book.firebaseapp.com',
    storageBucket: 'formula-e-book.appspot.com',
    measurementId: 'G-YB8YGVNEX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOi4Ts_vCDKaGK2jFW5hE-RgdkKR5bwRg',
    appId: '1:72236930132:android:79e3d65340ec59875049c1',
    messagingSenderId: '72236930132',
    projectId: 'formula-e-book',
    storageBucket: 'formula-e-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmcnVNYumaiulsy60HYLtcBeAgnUwFgi8',
    appId: '1:72236930132:ios:987256b43532d8185049c1',
    messagingSenderId: '72236930132',
    projectId: 'formula-e-book',
    storageBucket: 'formula-e-book.appspot.com',
    iosClientId: '72236930132-ocvlknm72d03c9i4irj33tbs915andpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.formulaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmcnVNYumaiulsy60HYLtcBeAgnUwFgi8',
    appId: '1:72236930132:ios:987256b43532d8185049c1',
    messagingSenderId: '72236930132',
    projectId: 'formula-e-book',
    storageBucket: 'formula-e-book.appspot.com',
    iosClientId: '72236930132-ocvlknm72d03c9i4irj33tbs915andpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.formulaApp',
  );
}
